spring:
  application:
    name: notification-service
  profiles:
    active: compose
  config:
    import: configserver:http://config-server:8888
    # configserver:http://localhost:8888 <- in case of running with docker compose
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: pass

notifier:
  mode: mock
  cron:
    daily: '0 0 20 * * *' # every day at 20:00
    weekly: '0 0 15 * * 0' # every sunday at 15:00
    monthly: '0 0 12 27 * *' # every 27th of the month
  email:
    sender:
      address: ${EMAIL_ADDRESS}
    auth:
      username: ${EMAIL_ADDRESS}
      password: ${EMAIL_PASSWORD}
    java-mail:
      'mail.smtp.host': smtp.gmail.com
      'mail.smtp.port': 465
      'mail.smtp.auth': true
      'mail.smtp.socketFactory.port': 465
      'mail.smtp.socketFactory.class': javax.net.ssl.SSLSocketFactory
    templates:
      workout-goal-missed: classpath:template/email/workout-goal-missed.html
      nutrition-goal-missed: classpath:template/email/nutrition-goal-missed.html
