spring:
  application:
    name: auth
  profiles:
    active: compose
  config:
    import: configserver:http://config-server:8888
    # configserver:http://localhost:8888 <- in case of running manually
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: pass

grpc:
  server:
    port: 7001 # unused, so might as well define it here
