spring:
  application:
    name: workout-service
  profiles:
    active: compose
  config:
    import: configserver:http://config-server:8888
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: pass

    # configserver:http://localhost:8888 <- in case of running manually
